name: Broken Links Check

on:
  push:
    branches:
      - main
      - master

jobs:
  broken_links_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Broken Links Crawler
        uses: ScholliYT/Broken-Links-Crawler-Action@v3
        with:
          website_url: 'pinknoiseplaylisting.com'
          exclude_url_prefix: 'mailto:,https://www.linkedin.com,https://linkedin.com'
          verbose: 'true'
          max_retry_time: 30
          max_retries: 5
          max_depth: 1
